const mongoose = require('mongoose');
const ServiceRequest = require('../models/ServiceRequest');
const User = require('../models/User');
require('dotenv').config();

async function createSingleTestRequest() {
  try {
    // Connect to MongoDB
    console.log('Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/imservices', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('✅ Connected to MongoDB\n');

    // Find a client user
    const client = await User.findOne({ role: 'client' });
    
    if (!client) {
      console.log('❌ No client user found!');
      console.log('Please create a client account first:');
      console.log('   1. Go to http://localhost:5173/signup');
      console.log('   2. Sign up with any email');
      console.log('   3. Then run this script again\n');
      await mongoose.connection.close();
      return;
    }

    console.log(`✅ Found client: ${client.name} (${client.email})\n`);

    // Create a test service request
    // Note: requestId will be auto-generated by the pre-save hook
    const serviceRequest = new ServiceRequest({
      client: client._id,
      clientName: client.name,
      clientEmail: client.email,
      clientCompany: client.company || 'Test Company Ltd',
      serviceType: 'breakdown_repair',
      machineModel: 'Haitian MA900',
      machineSerialNumber: 'TEST-SN-001',
      problemDescription: 'Machine heating system is malfunctioning. Temperature readings are inconsistent and injection pressure is fluctuating. This is affecting production quality and needs urgent attention.',
      priority: 'high',
      currentStatus: 'received',
      statusHistory: [{
        status: 'received',
        changedBy: client._id,
        changedByName: client.name,
        changedAt: new Date(),
        notes: 'Test service request submitted'
      }]
    });

    // Save the request - this triggers the pre-save hook to generate requestId
    await serviceRequest.save();

    console.log('═══════════════════════════════════════════════════════');
    console.log('🎉 Test Service Request Created Successfully!');
    console.log('═══════════════════════════════════════════════════════\n');
    console.log('📋 Request Details:');
    console.log(`   Request ID: ${serviceRequest.requestId}`);
    console.log(`   Client: ${client.name}`);
    console.log(`   Service Type: ${serviceRequest.serviceType}`);
    console.log(`   Priority: ${serviceRequest.priority.toUpperCase()}`);
    console.log(`   Status: ${serviceRequest.currentStatus}`);
    console.log(`   Created: ${serviceRequest.createdAt.toLocaleString()}\n`);
    
    console.log('💡 How to Track This Request:');
    console.log('   1. Login to Admin Dashboard: http://localhost:5173/login');
    console.log('   2. Click "Service Requests" tab');
    console.log(`   3. Find request: ${serviceRequest.requestId}`);
    console.log('   4. Click the eye icon (👁️) to open tracking view');
    console.log('   5. Test the 5-step process:\n');
    console.log('      Step 1: Initial Request Review');
    console.log('      Step 2: Assessment & Planning');
    console.log('      Step 3: Implementation');
    console.log('      Step 4: Quality Check');
    console.log('      Step 5: Final Review & Closure\n');

    await mongoose.connection.close();
    console.log('✅ Done!\n');
    
  } catch (error) {
    console.error('❌ Error:', error.message);
    await mongoose.connection.close();
    process.exit(1);
  }
}

console.log('╔════════════════════════════════════════════════════════╗');
console.log('║   Create Single Test Service Request                  ║');
console.log('╚════════════════════════════════════════════════════════╝\n');

createSingleTestRequest();
