const mongoose = require('mongoose');
const ServiceRequest = require('../models/ServiceRequest');
const User = require('../models/User');
require('dotenv').config();

// Sample service request data
const sampleRequests = [
  {
    serviceType: 'breakdown_repair',
    machineModel: 'Haitian MA900',
    machineSerialNumber: 'SN-2024-001',
    problemDescription: 'Machine is not heating properly. The temperature gauge shows inconsistent readings and the injection pressure is fluctuating. Need urgent repair as production is affected.',
    priority: 'high',
    preferredDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 days from now
    location: 'Factory Floor A, Building 2',
    additionalNotes: 'Machine has been in operation for 3 years. Last maintenance was 6 months ago.'
  },
  {
    serviceType: 'preventive_maintenance',
    machineModel: 'Sumitomo SE180DUZ',
    machineSerialNumber: 'SN-2023-045',
    problemDescription: 'Regular preventive maintenance required as per schedule. Need complete inspection, lubrication, and parts replacement if necessary.',
    priority: 'medium',
    preferredDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
    location: 'Factory Floor B, Building 1',
    additionalNotes: 'This is scheduled maintenance. No urgent issues.'
  },
  {
    serviceType: 'spare_parts',
    machineModel: 'Engel Victory 330',
    machineSerialNumber: 'SN-2022-089',
    problemDescription: 'Need replacement parts: Hydraulic seals (2 sets), Temperature sensors (3 units), and Injection nozzle (1 unit). Current parts showing wear and tear.',
    priority: 'medium',
    preferredDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // 5 days from now
    location: 'Factory Floor C, Building 3',
    additionalNotes: 'Please confirm parts availability before scheduling.'
  },
  {
    serviceType: 'technical_support',
    machineModel: 'Arburg Allrounder 520A',
    machineSerialNumber: 'SN-2024-012',
    problemDescription: 'Need technical consultation on optimizing cycle time and reducing energy consumption. Current cycle time is 45 seconds, want to improve to 35 seconds.',
    priority: 'low',
    preferredDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000), // 10 days from now
    location: 'Factory Floor A, Building 2',
    additionalNotes: 'Looking for efficiency improvements and cost reduction strategies.'
  },
  {
    serviceType: 'installation',
    machineModel: 'Haitian Mars II 200',
    machineSerialNumber: 'SN-2024-NEW',
    problemDescription: 'New machine installation required. Need complete setup including electrical connections, calibration, and operator training.',
    priority: 'high',
    preferredDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3 days from now
    location: 'Factory Floor D, Building 4 (New Expansion)',
    additionalNotes: 'Machine delivery expected in 2 days. Need immediate installation after delivery.'
  }
];

async function createTestServiceRequests() {
  try {
    // Connect to MongoDB
    console.log('Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/imservices', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('✅ Connected to MongoDB');

    // Find a client user (non-admin)
    console.log('\nFinding client users...');
    const clientUsers = await User.find({ role: 'client' }).limit(5);
    
    if (clientUsers.length === 0) {
      console.log('❌ No client users found in database!');
      console.log('Please create a client user first by signing up on the website.');
      await mongoose.connection.close();
      return;
    }

    console.log(`✅ Found ${clientUsers.length} client user(s)`);
    clientUsers.forEach((user, index) => {
      console.log(`   ${index + 1}. ${user.name} (${user.email})`);
    });

    // Create service requests for each sample
    console.log('\n📝 Creating test service requests...\n');
    const createdRequests = [];

    for (let i = 0; i < sampleRequests.length; i++) {
      // Cycle through clients if we have fewer clients than requests
      const client = clientUsers[i % clientUsers.length];
      
      // Note: requestId will be auto-generated by the pre-save hook
      const requestData = {
        ...sampleRequests[i],
        client: client._id,
        clientName: client.name,
        clientEmail: client.email,
        clientCompany: client.company || 'N/A',
        currentStatus: 'received',
        statusHistory: [{
          status: 'received',
          changedBy: client._id,
          changedByName: client.name,
          changedAt: new Date(),
          notes: 'Service request submitted by client'
        }]
      };

      const serviceRequest = new ServiceRequest(requestData);
      await serviceRequest.save();
      
      createdRequests.push(serviceRequest);
      
      console.log(`✅ Created: ${serviceRequest.requestId}`);
      console.log(`   Service: ${serviceRequest.serviceType}`);
      console.log(`   Client: ${client.name}`);
      console.log(`   Priority: ${serviceRequest.priority}`);
      console.log(`   Status: ${serviceRequest.currentStatus}`);
      console.log('');
    }

    console.log('═══════════════════════════════════════════════════════');
    console.log(`🎉 Successfully created ${createdRequests.length} test service requests!`);
    console.log('═══════════════════════════════════════════════════════\n');
    
    console.log('📋 Summary:');
    createdRequests.forEach((req, index) => {
      console.log(`   ${index + 1}. ${req.requestId} - ${req.serviceType} (${req.priority})`);
    });
    
    console.log('\n💡 Next Steps:');
    console.log('   1. Login to Admin Dashboard');
    console.log('   2. Click "Service Requests" tab');
    console.log('   3. You should see all the test requests');
    console.log('   4. Click the eye icon (👁️) to track each request');
    console.log('   5. Test the 5-step tracking process!\n');

    // Close connection
    await mongoose.connection.close();
    console.log('✅ Database connection closed');
    
  } catch (error) {
    console.error('❌ Error creating test service requests:', error);
    await mongoose.connection.close();
    process.exit(1);
  }
}

// Run the script
console.log('╔════════════════════════════════════════════════════════╗');
console.log('║     Create Test Service Requests - IM Services        ║');
console.log('╚════════════════════════════════════════════════════════╝\n');

createTestServiceRequests();
